### ISSUE TITLE
Warning message and dialog for changing selected channels in settings page

### ISSUE THREAD

**Issue by mehdi-torabiv** [TogetherCrew/frontend#74]
## Description
In order to provide a good user experience, it is important to warn the user that the task they are about to start takes a long time.

## Tasks
- [x] Should show a modal when [button name] is clicked
- [x] Should hide the modal when the cancel button is clicked
- [x] Should hide the modal when the X button is clicked
- [x] Should call the API endpoint when the Start data processing button is clicked

## Documentation
- https://www.figma.com/file/whU3PlyPvdoSWdhUYQW7e9/Community-Health?node-id=10030%3A8730&t=xRicHXD3yEYPu3pF-1
